# Generated by Django 3.2.3 on 2021-05-17 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210515_1723'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useraccount',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
